#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

$projectTempDir = __DIR__ . '/storage/app/php-temp';

if (! is_dir($projectTempDir)) {
	@mkdir($projectTempDir, 0775, true);
}

if (is_dir($projectTempDir)) {
	putenv('TMP=' . $projectTempDir);
	putenv('TEMP=' . $projectTempDir);
	putenv('TMPDIR=' . $projectTempDir);
	$_ENV['TMP'] = $projectTempDir;
	$_ENV['TEMP'] = $projectTempDir;
	$_ENV['TMPDIR'] = $projectTempDir;
	$_SERVER['TMP'] = $projectTempDir;
	$_SERVER['TEMP'] = $projectTempDir;
	$_SERVER['TMPDIR'] = $projectTempDir;
}

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
